export const formFields = {
    createCowRecord: [
        {
            id: '1',
            name: 'Cow Control Number',
            code: 'cow_control_number',
            place_holder: 'Control Number',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '2',
            name: 'Cow Type',
            code: 'cow_type',
            place_holder: 'Cow Type',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '3',
            name: 'Select Cow Gender',
            code: 'cow_gender',
            place_holder: 'Cow Gender',
            input_type: 'SELECT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [
                {
                    id: '1',
                    name: 'Male',
                    category_field: 'male'
                },
                {
                    id: '2',
                    name: 'Female',
                    category_field: 'female'
                }
            ],
            is_filterable: false,
        },
        {
            id: '4',
            name: 'Select Cow Status',
            code: 'status',
            place_holder: 'Status',
            input_type: 'SELECT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [
                {
                    id: '1',
                    name: 'Available',
                    category_field: 'available'
                },
                {
                    id: '2',
                    name: 'Sold',
                    category_field: 'sold'
                }
            ],
            is_filterable: false,
        },
        {
            id: '5',
            name: 'Date of Birth',
            code: 'date_birth',
            place_holder: 'Date of birth',
            input_type: 'DATE',
            field_type: 'date',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
    ],
    createStaffRecord: [
        {
            id: '1',
            name: 'First Name',
            code: 'first_name',
            place_holder: 'First Name',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '2',
            name: 'Last Name',
            code: 'last_name',
            place_holder: 'Last Name',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '3',
            name: 'Email',
            code: 'email',
            place_holder: 'Email',
            input_type: 'INPUT',
            field_type: 'email',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '4',
            name: 'Phone Number',
            code: 'phone_number',
            place_holder: 'Phone Number',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '5',
            name: 'Designation',
            code: 'designation',
            place_holder: 'Designation',
            input_type: 'SELECT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [
                {
                    id: '1',
                    name: 'Manager',
                    category_field: 'manager'
                },
                {
                    id: '2',
                    name: 'Worker',
                    category_field: 'worker'
                }
            ],
            is_filterable: false,
        },
        {
            id: '6',
            name: 'Username',
            code: 'username',
            place_holder: 'Username',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
          },
    ],
    createMilkCollectionRecord: [
        {
            id: '1',
            name: 'Cow Number',
            code: 'cow_number',
            place_holder: 'Cow number',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '2',
            name: 'Date',
            code: 'date',
            place_holder: 'Date Collected',
            input_type: 'DATE',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '3',
            name: 'Liters',
            code: 'liters',
            place_holder: 'Liters',
            input_type: 'INPUT',
            field_type: 'number',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        }
    ],
    createCowSaleRecord: [
        {
            id: '1',
            name: 'Cow Number',
            code: 'cow_number',
            place_holder: 'Cow number',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '2',
            name: 'Date',
            code: 'date',
            place_holder: 'Date Sold',
            input_type: 'DATE',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '3',
            name: 'Amount',
            code: 'amount',
            place_holder: 'Amount',
            input_type: 'INPUT',
            field_type: 'number',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '4',
            name: 'Customer Name',
            code: 'customer_name',
            place_holder: 'Customer Name',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '5',
            name: 'Customer Phone',
            code: 'customer_phone_number',
            place_holder: 'Customer Contact',
            input_type: 'INPUT',
            field_type: 'text',
            category: '',
            required: true,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '6',
            name: 'Customer Email',
            code: 'customer_email',
            place_holder: 'Customer Email',
            input_type: 'INPUT',
            field_type: 'email',
            category: '',
            required: false,
            field_options: [],
            is_filterable: false,
        },
        {
            id: '7',
            name: 'Remarks',
            code: 'remarks',
            place_holder: 'Remarks',
            input_type: 'TEXTAREA',
            field_type: 'text',
            category: '',
            required: false,
            field_options: [],
            is_filterable: false,
        }
    ]
}